"""
Canonical data model for the patient timeline.

Every fact shown to a user is an Event. Every Event carries Evidence
pointing back to the exact source table/row it came from. Events that
are a grouping of other events (e.g. a cluster of 14 lab draws) are
marked is_derived=True and list their raw children -- so the UI never
has to guess whether something came straight from the record or was
generated by our code.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


class Evidence(BaseModel):
    """A pointer back to the exact source row that supports an event."""

    source_table: str
    source_fields: dict[str, Any]


class Event(BaseModel):
    event_id: str

    subject_id: int
    hadm_id: Optional[int] = None
    stay_id: Optional[int] = None

    event_time: Optional[datetime] = None
    event_end_time: Optional[datetime] = None

    # ADMISSION | DISCHARGE | TRANSFER | LAB | LAB_CLUSTER | MEDICATION |
    # DIAGNOSIS | PROCEDURE | ICU_STAY | ICU_OBSERVATION | ICU_OBSERVATION_CLUSTER
    event_type: str
    event_subtype: Optional[str] = None

    label: str
    value: Optional[str] = None
    unit: Optional[str] = None

    # True if this event is a computed grouping rather than a single
    # source row (e.g. a cluster of labs drawn in the same 15 minutes).
    is_derived: bool = False
    derivation_rule: Optional[str] = None
    children: list["Event"] = Field(default_factory=list)

    evidence: list[Evidence] = Field(default_factory=list)

    @field_validator("value", "unit", mode="before")
    @classmethod
    def _stringify(cls, v):
        # Source columns are typed inconsistently across MIMIC tables
        # (dose_val_rx, valuenum, etc. can come back as int/float/Decimal
        # depending on DuckDB's type inference) -- normalize to str so the
        # model never rejects a perfectly good value over its Python type.
        return None if v is None else str(v)


Event.model_rebuild()


class Timeline(BaseModel):
    subject_id: int
    hadm_id: Optional[int] = None
    stay_id: Optional[int] = None

    events: list[Event]
    event_count: int
    tables_used: list[str]

    # Anything we looked for but genuinely found no rows for -- surfaced
    # explicitly rather than silently omitted, per the abstention
    # requirement in the challenge brief.
    empty_sources: list[str] = Field(default_factory=list)