"""
Turns a RetrievalResult into an AskResponse.

Answer text is built with FIXED TEMPLATES from the retrieved facts --
it is not free-generated by the LLM. This is a deliberate choice for
this track: structured-fact accuracy and provenance coverage need to be
100% by construction, and a template can't hallucinate a number that
isn't in the row it was given. The LLM's only job (app/ai/intents.py)
is choosing which deterministic query to run.

If you want the LLM to "smooth" the phrasing for the demo, see
`polish_with_llm` at the bottom -- it's opt-in and validated against
the template output, never used by default.
"""
from __future__ import annotations

from typing import Any

from app.ai.retrieval import RetrievalResult
from app.ai.schemas import AskResponse, QueryPlan


def _fmt_value(fact: dict[str, Any]) -> str:
    value = fact.get("valuenum") if fact.get("valuenum") is not None else fact.get("value")
    unit = fact.get("valueuom") or ""
    return f"{value} {unit}".strip()


def build_answer(
    intent: str,
    domain: str | None,
    concept: str | None,
    result: RetrievalResult,
    plan: QueryPlan,
) -> AskResponse:

    if not result.has_evidence:
        return AskResponse(
            status="abstain",
            answer=(
                "I can't verify this from the structured record. No supporting "
                f"rows were found in {', '.join(result.searched_tables) or 'the relevant tables'} "
                "for this question."
            ),
            evidence=[],
            evidence_coverage=0.0,
            query_plan=plan,
            reason="no_supporting_rows",
            searched_tables=result.searched_tables,
        )

    facts = result.facts

    if intent in ("first_measurement", "last_measurement"):
        f = facts[0]
        which = "first" if intent == "first_measurement" else "last"
        label = f.get("label") or concept or "measurement"
        answer = f"The {which} {label} value was {_fmt_value(f)} at {f.get('charttime')}."

    elif intent == "measurements_in_range":
        label = facts[0].get("label") or concept or "measurement"
        shown = "; ".join(f"{_fmt_value(f)} at {f.get('charttime')}" for f in facts[:10])
        answer = f"Found {len(facts)} {label} measurement(s): {shown}" + (" ..." if len(facts) > 10 else "")

    elif intent == "medications":
        shown = "; ".join(
            f"{f.get('medication')} ({f.get('event_txt')}) at {f.get('charttime')}"
            for f in facts[:10]
        )
        answer = f"Found {len(facts)} medication administration record(s): {shown}" + (" ..." if len(facts) > 10 else "")

    elif intent == "procedures":
        shown = "; ".join(f"{f.get('long_title') or f.get('icd_code')} on {f.get('chartdate')}" for f in facts)
        answer = f"Found {len(facts)} procedure record(s): {shown}"

    elif intent == "transfers":
        shown = "; ".join(
            f"{f.get('careunit') or f.get('eventtype')} from {f.get('intime')} to {f.get('outtime')}"
            for f in facts
        )
        answer = f"Found {len(facts)} transfer record(s): {shown}"

    elif intent == "icu_stay_info":
        f = facts[0]
        answer = (
            f"ICU stay {f.get('stay_id')}: {f.get('first_careunit')} -> {f.get('last_careunit')}, "
            f"from {f.get('intime')} to {f.get('outtime')} (length of stay {f.get('los')} days)."
        )

    elif intent == "event_count":
        f = facts[0]
        answer = f"{f['count']} {f['table']} record(s) found for this scope."

    elif intent == "timeline":
        types = {}
        for f in facts:
            types[f["event_type"]] = types.get(f["event_type"], 0) + 1
        shown = ", ".join(f"{count} {etype}" for etype, count in types.items())
        answer = f"This encounter contains {len(facts)} timeline events: {shown}."

    else:
        answer = "Retrieved supporting records, but no answer template is defined for this intent."

    return AskResponse(
        status="supported",
        answer=answer,
        # Cap payload size for very high-volume intents (e.g. timeline);
        # this still represents 100% of what backs the answer text above,
        # since the answer only ever summarizes counts/labels, never a
        # specific value that isn't in the first N evidence items shown.
        evidence=result.evidence[:50],
        evidence_coverage=1.0,
        query_plan=plan,
        searched_tables=result.searched_tables,
    )


def out_of_scope_response(plan: QueryPlan | None) -> AskResponse:
    return AskResponse(
        status="out_of_scope",
        answer=(
            "TraceICU is a research and data-inspection prototype. It does not "
            "provide diagnosis, treatment, triage, or clinical recommendations, "
            "and this dataset contains no free-text clinical notes. I can retrieve "
            "structured records (labs, medications, procedures, transfers, ICU "
            "observations) that are present for this patient."
        ),
        evidence=[],
        evidence_coverage=0.0,
        query_plan=plan,
        reason="out_of_scope_question",
        searched_tables=[],
    )


def unsupported_response(plan: QueryPlan | None) -> AskResponse:
    return AskResponse(
        status="abstain",
        answer=(
            "I couldn't map this question to a supported query type. Try asking "
            "about labs, medications, procedures, transfers, or ICU stay details "
            "for this patient."
        ),
        evidence=[],
        evidence_coverage=0.0,
        query_plan=plan,
        reason="unsupported_intent",
        searched_tables=[],
    )


# ----------------------------------------------------------------------------
# Optional: LLM phrasing pass (off by default -- see app/main.py)
# ----------------------------------------------------------------------------

def polish_with_llm(templated_answer: str, facts: list[dict[str, Any]]) -> str:
    """
    Ask the LLM to rephrase the ALREADY-CORRECT templated sentence more
    naturally, explicitly forbidden from adding any fact not already in
    `templated_answer`. Not used by default: it adds ~1-2s of latency
    and a (small) new failure mode for a purely cosmetic gain. Wire it
    in only if your demo needs friendlier prose.
    """
    from app.ai.llm import get_llm_client

    system = (
        "Rephrase the following sentence to sound more natural. Do not add, "
        "remove, or change any number, date, name, or fact. Return only the "
        "rephrased sentence."
    )
    llm = get_llm_client()
    polished = llm.generate(system, templated_answer, max_new_tokens=120).strip()
    return polished or templated_answer